kind: SylvaWorkloadCluster
apiVersion: workloadclusteroperator.sylva/v1alpha1
metadata:
  name: swc
  namespace: wc-1
spec:
  k8sVersion: "1.28"
  infrastructure: openstack
  controlPlane:
    provider: rke2
    replicas: 1
  machineDeployments:
    my-md1-name:
      replicas: 1
  enabledUnits:
    multus: true
  clusterSettings:
    capo:
      ssh_key_name: mgmt_key
      image_key: ubuntu-jammy-hardened-rke2-1-28-12
      network_id: 489b1587-4aa4-49b2-be56-62af67efa68f
      flavor_name: "B1.xlarge"
