apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: team-secret-store
  namespace: {{ $nsName }}
  labels: {{- include "workload-team-defs.labels" $ | nindent 4 }}
spec:
  provider:
    vault:
      server: "https://vault.vault.svc.cluster.local:8200"
      path: {{ $nsName }}
      version: v2
      caProvider:
        type: Secret
        name: sylva-ca.crt
        key: ca.crt
      auth:
        kubernetes:
          mountPath: kubernetes
          role: {{ $nsName }}
          serviceAccountRef:
            name: secretstore-access-{{ $name }}
{{- end}}
